export default function createModuleConfig({ datasets, user, moeda, dataBr }) {
  return {
    pessoas: {
      title: 'Pessoas e Empresas',
      route: '/api/pessoas',
      dataKey: 'pessoas',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Pessoa</>,
      fields: [
        { name: 'tipo', label: 'Tipo', type: 'select', options: [{ value: 'Física', label: 'Física' }, { value: 'Jurídica', label: 'Jurídica' }] },
        { name: 'nome', label: 'Nome', type: 'text', required: true },
        { name: 'documento', label: 'Documento', type: 'text' },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'telefone', label: 'Telefone', type: 'text' },
      ],
      defaults: { tipo: 'Física', nome: '', documento: '', email: '', telefone: '' },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'tipo', label: 'Tipo' },
        { key: 'nome', label: 'Nome' },
        { key: 'documento', label: 'Documento', render: (row) => row.documento || '-' },
        { key: 'email', label: 'Email', render: (row) => row.email || '-' },
        { key: 'telefone', label: 'Telefone', render: (row) => row.telefone || '-' },
      ],
    },
    categorias: {
      title: 'Categorias',
      route: '/api/categorias',
      dataKey: 'categorias',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Categoria</>,
      fields: [
        { name: 'nome', label: 'Nome', type: 'text', required: true },
        { name: 'tipo', label: 'Tipo', type: 'select', options: [{ value: 'despesa', label: 'Despesa' }, { value: 'receita', label: 'Receita' }] },
        { name: 'cor', label: 'Cor', type: 'color' },
      ],
      defaults: { nome: '', tipo: 'despesa', cor: '#667eea' },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'nome', label: 'Nome' },
        { key: 'tipo', label: 'Tipo' },
        { key: 'cor', label: 'Cor', render: (row) => <span className="color-pill" style={{ background: row.cor || '#667eea' }}>{row.cor || '#667eea'}</span> },
        { key: 'ativo', label: 'Ativo', render: (row) => (Number(row.ativo) === 1 ? 'Sim' : 'Não') },
      ],
    },
    contas: {
      title: 'Contas Caixa',
      route: '/api/contas-caixa',
      dataKey: 'contas',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Conta</>,
      fields: [
        { name: 'nome', label: 'Nome', type: 'text', required: true },
        { name: 'banco', label: 'Banco', type: 'text' },
        { name: 'agencia', label: 'Agência', type: 'text' },
        { name: 'conta', label: 'Conta', type: 'text' },
        { name: 'saldo', label: 'Saldo', type: 'number', step: '0.01' },
      ],
      defaults: { nome: '', banco: '', agencia: '', conta: '', saldo: '0.00' },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'nome', label: 'Nome' },
        { key: 'banco', label: 'Banco', render: (row) => row.banco || '-' },
        { key: 'agencia', label: 'Agência', render: (row) => row.agencia || '-' },
        { key: 'conta', label: 'Conta', render: (row) => row.conta || '-' },
        { key: 'saldo', label: 'Saldo', render: (row) => moeda(row.saldo) },
      ],
    },
    financeiro: {
      title: 'Financeiro',
      route: '/api/financeiro',
      dataKey: 'financeiro',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Lançamento</>,
      fields: [
        { name: 'pessoa_id', label: 'Pessoa', type: 'select', quickAdd: 'pessoas', options: datasets.pessoas.map((item) => ({ value: String(item.id), label: item.nome })) },
        { name: 'categoria_id', label: 'Categoria', type: 'select', quickAdd: 'categorias', options: datasets.categorias.map((item) => ({ value: String(item.id), label: `${item.nome} · ${item.tipo}` })) },
        { name: 'conta_caixa_id', label: 'Conta Caixa', type: 'select', quickAdd: 'contas', options: datasets.contas.map((item) => ({ value: String(item.id), label: item.nome })) },
        { name: 'valor', label: 'Valor', type: 'number', step: '0.01', min: '0.01', required: true },
        { name: 'data_vencimento', label: 'Vencimento', type: 'date', required: true },
      ],
      defaults: {
        pessoa_id: datasets.pessoas[0] ? String(datasets.pessoas[0].id) : '',
        categoria_id: datasets.categorias[0] ? String(datasets.categorias[0].id) : '',
        conta_caixa_id: datasets.contas[0] ? String(datasets.contas[0].id) : '',
        valor: '',
        data_vencimento: new Date().toISOString().slice(0, 10),
      },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'tipo', label: 'Tipo' },
        { key: 'status', label: 'Status' },
        { key: 'pessoa_nome', label: 'Pessoa', render: (row) => row.pessoa_nome || '-' },
        { key: 'categoria_nome', label: 'Categoria', render: (row) => row.categoria_nome || '-' },
        { key: 'conta_nome', label: 'Conta', render: (row) => row.conta_nome || '-' },
        { key: 'valor', label: 'Valor', render: (row) => moeda(row.valor) },
        { key: 'data_vencimento', label: 'Vencimento', render: (row) => dataBr(row.data_vencimento) },
      ],
    },
    cofrinhos: {
      title: 'Cofrinhos',
      route: '/api/cofrinhos',
      dataKey: 'cofrinhos',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Cofrinho</>,
      fields: [
        { name: 'nome', label: 'Nome', type: 'text', required: true },
        { name: 'saldo_atual', label: 'Saldo Atual', type: 'number', step: '0.01' },
        { name: 'valor_objetivo', label: 'Objetivo', type: 'number', step: '0.01', required: true },
        { name: 'meses_meta', label: 'Meses da Meta', type: 'number', min: '1', required: true },
      ],
      defaults: { nome: '', saldo_atual: '0.00', valor_objetivo: '', meses_meta: '1' },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'nome', label: 'Nome' },
        { key: 'saldo_atual', label: 'Saldo Atual', render: (row) => moeda(row.saldo_atual) },
        { key: 'valor_objetivo', label: 'Objetivo', render: (row) => moeda(row.valor_objetivo) },
        { key: 'meses_meta', label: 'Meses' },
        { key: 'valor_mensal_necessario', label: 'Aporte Mensal', render: (row) => moeda(row.valor_mensal_necessario) },
      ],
    },
    aportes: {
      title: 'Aportes dos Cofrinhos',
      route: '/api/cofrinhos/aportes',
      dataKey: 'aportes',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Aporte</>,
      fields: [
        { name: 'id_cofrinho', label: 'Cofrinho', type: 'select', options: datasets.cofrinhos.map((item) => ({ value: String(item.id), label: item.nome })) },
        { name: 'valor', label: 'Valor', type: 'number', step: '0.01', required: true },
        { name: 'data_aporte', label: 'Data', type: 'date', required: true },
        { name: 'observacao', label: 'Observação', type: 'text' },
      ],
      defaults: {
        id_cofrinho: datasets.cofrinhos[0] ? String(datasets.cofrinhos[0].id) : '',
        valor: '',
        data_aporte: new Date().toISOString().slice(0, 10),
        observacao: '',
      },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'cofrinho_nome', label: 'Cofrinho' },
        { key: 'valor', label: 'Valor', render: (row) => moeda(row.valor) },
        { key: 'data_aporte', label: 'Data', render: (row) => dataBr(row.data_aporte) },
        { key: 'observacao', label: 'Observação', render: (row) => row.observacao || '-' },
      ],
    },
    usuarios: {
      title: 'Usuários',
      route: '/api/admin/usuarios',
      dataKey: 'usuarios',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Usuário</>,
      fields: [
        { name: 'nome', label: 'Nome', type: 'text', required: true },
        { name: 'senha', label: 'Senha', type: 'password' },
        { name: 'perfil', label: 'Perfil', type: 'select', options: user?.perfil === 'root' ? [{ value: 'user', label: 'User' }, { value: 'admin', label: 'Admin' }, { value: 'root', label: 'Root' }] : [{ value: 'user', label: 'User' }, { value: 'admin', label: 'Admin' }] },
        ...(user?.perfil === 'root' ? [{ name: 'id_entidade', label: 'Entidade', type: 'select', options: datasets.entidades.map((item) => ({ value: String(item.id), label: item.nome })) }] : []),
        { name: 'datalimite', label: 'Validade', type: 'date', required: true },
      ],
      defaults: {
        nome: '',
        senha: '',
        perfil: 'user',
        id_entidade: user?.perfil === 'root' && datasets.entidades[0] ? String(datasets.entidades[0].id) : String(user?.id_entidade || ''),
        datalimite: new Date().toISOString().slice(0, 10),
      },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'nome', label: 'Nome' },
        { key: 'perfil', label: 'Perfil' },
        { key: 'entidade_nome', label: 'Entidade' },
        { key: 'datalimite', label: 'Validade', render: (row) => dataBr(row.datalimite) },
      ],
    },
    entidades: {
      title: 'Entidades',
      route: '/api/root/entidades',
      dataKey: 'entidades',
      createLabel: <><i className="fas fa-plus" aria-hidden="true" /> Entidade</>,
      fields: [
        { name: 'nome', label: 'Nome', type: 'text', required: true },
        { name: 'datalimite', label: 'Data Limite', type: 'date', required: true },
      ],
      defaults: { nome: '', datalimite: new Date().toISOString().slice(0, 10) },
      columns: [
        { key: 'id', label: 'ID' },
        { key: 'nome', label: 'Nome' },
        { key: 'datalimite', label: 'Data Limite', render: (row) => dataBr(row.datalimite) },
      ],
    },
  }
}